#!/usr/bin/env node
import { spawnSync } from 'node:child_process'
import { lstat, readFile, realpath, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { canonicalJson, sha256 } from '../../eval/v0.4/lib/canonical.mjs'
import { verifyExecutionEnvelope } from './design.mjs'
import { assertExecutionFreeze, studySourceDigest } from './integrity.mjs'
import { loadStudySpec, repositoryRoot } from './protocol.mjs'

export const RC4_PUBLIC_ATTESTATION = Object.freeze({
  protocol: 'plan-lattice-rc4-public-freeze-anchor-v1',
  repository: '1052326311/dsh-plan-lattice',
  repositoryUrl: 'https://github.com/1052326311/dsh-plan-lattice',
  workflowPath: '.github/workflows/attest-rc4-freezes.yml',
  signerWorkflow: '1052326311/dsh-plan-lattice/.github/workflows/attest-rc4-freezes.yml',
  study: Object.freeze({
    kind: 'study',
    tag: 'model-rc4-study-protocol-freeze-v2',
    ref: 'refs/tags/model-rc4-study-protocol-freeze-v2',
  }),
  execution: Object.freeze({
    kind: 'execution',
    tag: 'model-rc4-execution-freeze',
    ref: 'refs/tags/model-rc4-execution-freeze',
  }),
})

function exactKind(kind) {
  const record = RC4_PUBLIC_ATTESTATION[kind]
  if (!record || !['study', 'execution'].includes(kind)) throw new Error('public freeze anchor kind must be study or execution')
  return record
}

function exactHex(value, length, label) {
  if (!new RegExp(`^[a-f0-9]{${length}}$`, 'u').test(value ?? '')) throw new Error(`${label} is invalid`)
  return value
}

function exactInteger(value, label) {
  const number = Number(value)
  if (!Number.isSafeInteger(number) || number < 1) throw new Error(`${label} is invalid`)
  return number
}

function git(args, { binary = false } = {}) {
  const result = spawnSync('git', ['-C', repositoryRoot, ...args], {
    encoding: binary ? undefined : 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  if (result.status !== 0) throw new Error(`git ${args[0]} failed while building the public freeze anchor`)
  return result.stdout
}

function productionDependencies(overrides = {}) {
  return {
    git,
    loadStudySpec,
    studySourceDigest,
    verifyExecutionEnvelope,
    assertExecutionFreeze,
    spawnSync,
    ...overrides,
  }
}

function gitIdentity(ref, deps) {
  const refObject = String(deps.git(['rev-parse', ref])).trim()
  const commit = String(deps.git(['rev-parse', `${ref}^{commit}`])).trim()
  const tree = String(deps.git(['rev-parse', `${commit}^{tree}`])).trim()
  return {
    refObject: exactHex(refObject, 40, 'tag object'),
    commit: exactHex(commit, 40, 'tag commit'),
    tree: exactHex(tree, 40, 'tag tree'),
  }
}

function workflowIdentity(commit, studyCommit, deps) {
  const current = deps.git(['show', `${commit}:${RC4_PUBLIC_ATTESTATION.workflowPath}`], { binary: true })
  const study = deps.git(['show', `${studyCommit}:${RC4_PUBLIC_ATTESTATION.workflowPath}`], { binary: true })
  if (sha256(current) !== sha256(study)) throw new Error('attestation workflow changed after the study freeze')
  return { path: RC4_PUBLIC_ATTESTATION.workflowPath, sha256: sha256(current) }
}

function githubIdentity(kind, source, environment) {
  const expected = exactKind(kind)
  if (environment.GITHUB_ACTIONS !== 'true'
    || environment.GITHUB_REPOSITORY !== RC4_PUBLIC_ATTESTATION.repository
    || environment.GITHUB_REF !== expected.ref
    || environment.GITHUB_REF_NAME !== expected.tag
    || environment.GITHUB_EVENT_NAME !== 'push'
    || environment.RUNNER_ENVIRONMENT !== 'github-hosted') {
    throw new Error('public freeze anchor must be generated by the exact GitHub-hosted tag workflow')
  }
  const sourceDigest = exactHex(environment.GITHUB_SHA, 40, 'GitHub source digest')
  if (![source.commit, source.refObject].includes(sourceDigest)) throw new Error('GitHub source digest does not resolve to the frozen tag')
  if (exactInteger(environment.GITHUB_RUN_ATTEMPT, 'GitHub run attempt') !== 1) {
    throw new Error('public freeze anchor accepts only the first workflow attempt')
  }
  const workflowRef = String(environment.GITHUB_WORKFLOW_REF ?? '')
  if (!workflowRef.startsWith(`${RC4_PUBLIC_ATTESTATION.repository}/${RC4_PUBLIC_ATTESTATION.workflowPath}@`)) {
    throw new Error('GitHub workflow identity is invalid')
  }
  return {
    event: 'push',
    repository: environment.GITHUB_REPOSITORY,
    runId: exactInteger(environment.GITHUB_RUN_ID, 'GitHub run ID'),
    runAttempt: 1,
    runnerEnvironment: 'github-hosted',
    sourceDigest,
    workflowRef,
  }
}

function readTaggedExecutionEnvelope(commit, studySpec, deps) {
  const bytes = deps.git(['show', `${commit}:${studySpec.executionFreeze.evidencePath}`], { binary: true })
  const text = bytes.toString('utf8')
  const envelope = JSON.parse(text)
  if (canonicalJson(envelope) !== text) throw new Error('execution envelope in the public tag is not canonical')
  deps.verifyExecutionEnvelope(envelope, studySpec)
  deps.assertExecutionFreeze(envelope, studySpec)
  return { bytes, envelope }
}

export async function buildPublicFreezeAnchor(kind, options = {}, overrides = {}) {
  const expected = exactKind(kind)
  const deps = productionDependencies(overrides)
  const { spec: studySpec } = await deps.loadStudySpec()
  const source = gitIdentity(expected.ref, deps)
  const study = gitIdentity(studySpec.studyProtocolFreeze.publicRef, deps)
  if (kind === 'study' && study.commit !== source.commit) throw new Error('study freeze identity is inconsistent')
  if (kind === 'execution') {
    const ancestry = deps.git(['merge-base', '--is-ancestor', study.commit, source.commit])
    void ancestry
  }
  const protectedSource = deps.studySourceDigest(study.commit)
  const anchor = {
    schemaVersion: 1,
    protocol: RC4_PUBLIC_ATTESTATION.protocol,
    kind,
    repository: RC4_PUBLIC_ATTESTATION.repository,
    repositoryUrl: RC4_PUBLIC_ATTESTATION.repositoryUrl,
    tag: expected.tag,
    ref: expected.ref,
    source,
    studyFreeze: {
      commit: study.commit,
      tree: study.tree,
      protectedSourceDigest: protectedSource.digest,
      protectedSourceFileCount: protectedSource.files.length,
    },
    workflow: workflowIdentity(source.commit, study.commit, deps),
    github: githubIdentity(kind, source, options.environment ?? process.env),
  }
  if (kind === 'study') {
    anchor.rawEvidence = {
      status: 'not-revealed-at-study-freeze',
      v13: null,
      v14: null,
    }
  } else {
    const { bytes, envelope } = readTaggedExecutionEnvelope(source.commit, studySpec, deps)
    const router = envelope.routerEvidence
    anchor.executionFreeze = {
      envelopePath: studySpec.executionFreeze.evidencePath,
      envelopeSha256: sha256(bytes),
      envelopeDigest: envelope.envelopeDigest,
      manifestDigest: envelope.runManifest.manifestDigest,
      candidateCommit: envelope.candidateCommit,
      signingLedgerId: envelope.signingLedgerId,
    }
    anchor.rawEvidence = {
      status: 'immutable-v13-v14-commitments',
      routerEvidenceSha256: sha256(router),
      v13: { outcomeSha256: router.v13OutcomeSha256 },
      v14: {
        attemptSha256: router.v14AttemptSha256,
        resultSha256: router.v14ResultSha256,
        recomputedRowsSha256: router.recomputedRowsSha256,
      },
    }
  }
  return anchor
}

function same(actual, expected, label) {
  if (canonicalJson(actual) !== canonicalJson(expected)) throw new Error(`${label} differs from the public freeze`)
}

export async function verifyPublicFreezeAnchor(anchor, overrides = {}) {
  const expectedKind = exactKind(anchor?.kind)
  const deps = productionDependencies(overrides)
  const { spec: studySpec } = await deps.loadStudySpec()
  if (anchor.schemaVersion !== 1
    || anchor.protocol !== RC4_PUBLIC_ATTESTATION.protocol
    || anchor.repository !== RC4_PUBLIC_ATTESTATION.repository
    || anchor.repositoryUrl !== RC4_PUBLIC_ATTESTATION.repositoryUrl
    || anchor.tag !== expectedKind.tag
    || anchor.ref !== expectedKind.ref) {
    throw new Error('public freeze anchor identity is invalid')
  }
  const source = gitIdentity(expectedKind.ref, deps)
  same(anchor.source, source, 'tag source')
  const study = gitIdentity(studySpec.studyProtocolFreeze.publicRef, deps)
  const protectedSource = deps.studySourceDigest(study.commit)
  same(anchor.studyFreeze, {
    commit: study.commit,
    tree: study.tree,
    protectedSourceDigest: protectedSource.digest,
    protectedSourceFileCount: protectedSource.files.length,
  }, 'study source')
  same(anchor.workflow, workflowIdentity(source.commit, study.commit, deps), 'attestation workflow')
  if (anchor.github?.repository !== RC4_PUBLIC_ATTESTATION.repository
    || anchor.github.event !== 'push'
    || anchor.github.runAttempt !== 1
    || anchor.github.runnerEnvironment !== 'github-hosted'
    || ![source.commit, source.refObject].includes(anchor.github.sourceDigest)
    || !String(anchor.github.workflowRef ?? '').startsWith(`${RC4_PUBLIC_ATTESTATION.repository}/${RC4_PUBLIC_ATTESTATION.workflowPath}@`)) {
    throw new Error('public freeze anchor GitHub build identity is invalid')
  }
  exactInteger(anchor.github.runId, 'anchor GitHub run ID')
  if (anchor.kind === 'study') {
    same(anchor.rawEvidence, { status: 'not-revealed-at-study-freeze', v13: null, v14: null }, 'study evidence state')
  } else {
    const { bytes, envelope } = readTaggedExecutionEnvelope(source.commit, studySpec, deps)
    const router = envelope.routerEvidence
    same(anchor.executionFreeze, {
      envelopePath: studySpec.executionFreeze.evidencePath,
      envelopeSha256: sha256(bytes),
      envelopeDigest: envelope.envelopeDigest,
      manifestDigest: envelope.runManifest.manifestDigest,
      candidateCommit: envelope.candidateCommit,
      signingLedgerId: envelope.signingLedgerId,
    }, 'execution envelope')
    same(anchor.rawEvidence, {
      status: 'immutable-v13-v14-commitments',
      routerEvidenceSha256: sha256(router),
      v13: { outcomeSha256: router.v13OutcomeSha256 },
      v14: {
        attemptSha256: router.v14AttemptSha256,
        resultSha256: router.v14ResultSha256,
        recomputedRowsSha256: router.recomputedRowsSha256,
      },
    }, 'raw V13/V14 evidence commitments')
  }
  return { kind: anchor.kind, sourceCommit: source.commit, sourceRef: expectedKind.ref }
}

async function exactRegularFile(path, label) {
  if (!isAbsolute(path ?? '')) throw new Error(`${label} must be an absolute path`)
  const absolute = resolve(path)
  const metadata = await lstat(absolute)
  if (!metadata.isFile() || metadata.isSymbolicLink()) {
    throw new Error(`${label} must be a regular non-symlink file`)
  }
  return realpath(absolute)
}

function verifyTransparency(result) {
  if (!Array.isArray(result) || result.length === 0) throw new Error('GitHub returned no verified provenance')
  const timestamps = result.flatMap(entry => entry?.verificationResult?.verifiedTimestamps ?? [])
  if (timestamps.length === 0) throw new Error('GitHub provenance has no transparency-log or timestamp witness')
  return { attestations: result.length, verifiedTimestamps: timestamps.length }
}

export async function verifyPublicFreezeAttestation({ kind, anchorPath, bundlePath }, overrides = {}) {
  const deps = productionDependencies(overrides)
  const anchorFile = await exactRegularFile(anchorPath, `${kind} anchor`)
  const bytes = await readFile(anchorFile)
  const anchor = JSON.parse(bytes)
  if (canonicalJson(anchor) !== bytes.toString('utf8')) throw new Error(`${kind} anchor is not canonical JSON`)
  const semantic = await verifyPublicFreezeAnchor(anchor, deps)
  const args = [
    'attestation', 'verify', anchorFile,
    '--repo', RC4_PUBLIC_ATTESTATION.repository,
    '--signer-workflow', RC4_PUBLIC_ATTESTATION.signerWorkflow,
    '--source-ref', semantic.sourceRef,
    '--source-digest', anchor.github.sourceDigest,
    '--deny-self-hosted-runners',
    '--format', 'json',
  ]
  if (bundlePath) args.push('--bundle', await exactRegularFile(bundlePath, `${kind} attestation bundle`))
  const result = deps.spawnSync('gh', args, {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    env: process.env,
  })
  if (result.status !== 0) throw new Error(`${kind} GitHub Sigstore provenance verification failed`)
  let verification
  try {
    verification = verifyTransparency(JSON.parse(result.stdout))
  } catch (error) {
    throw new Error(`${kind} GitHub provenance output is invalid: ${String(error?.message ?? error)}`)
  }
  return {
    kind,
    anchorSha256: sha256(bytes),
    sourceCommit: semantic.sourceCommit,
    ...verification,
  }
}

export function publicEvidenceSummary(anchor) {
  return {
    schemaVersion: 1,
    protocol: RC4_PUBLIC_ATTESTATION.protocol,
    kind: anchor.kind,
    repository: anchor.repository,
    ref: anchor.ref,
    sourceCommit: anchor.source.commit,
    studyCommit: anchor.studyFreeze.commit,
    protectedSourceDigest: anchor.studyFreeze.protectedSourceDigest,
    ...(anchor.executionFreeze ? { executionFreeze: anchor.executionFreeze } : {}),
    rawEvidence: anchor.rawEvidence,
  }
}

function option(args, name) {
  const index = args.indexOf(name)
  return index === -1 ? undefined : args[index + 1]
}

function isMain() {
  return process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url
}

if (isMain()) {
  const args = process.argv.slice(2)
  const command = args[0]
  if (command === 'create') {
    const kind = option(args, '--kind')
    const output = resolve(option(args, '--out') ?? '')
    const summaryOutput = resolve(option(args, '--summary-out') ?? '')
    const checksumOutput = resolve(option(args, '--sha256-out') ?? '')
    if (!option(args, '--out') || !option(args, '--summary-out') || !option(args, '--sha256-out')) {
      throw new Error('create requires --kind, --out, --summary-out, and --sha256-out')
    }
    const anchor = await buildPublicFreezeAnchor(kind)
    const bytes = canonicalJson(anchor)
    await writeFile(output, bytes, { encoding: 'utf8', mode: 0o644 })
    await writeFile(summaryOutput, canonicalJson(publicEvidenceSummary(anchor)), { encoding: 'utf8', mode: 0o644 })
    await writeFile(checksumOutput, `${sha256(bytes)}  ${output.slice(dirname(output).length + 1)}\n`, { encoding: 'utf8', mode: 0o644 })
    process.stdout.write(canonicalJson({ kind, anchorSha256: sha256(bytes), paidModelInvocations: 0 }))
  } else if (command === 'verify') {
    const result = await verifyPublicFreezeAttestation({
      kind: option(args, '--kind'),
      anchorPath: option(args, '--anchor'),
      bundlePath: option(args, '--bundle'),
    })
    process.stdout.write(canonicalJson({ ...result, paidModelInvocations: 0 }))
  } else if (command === 'verify-local') {
    const anchorPath = await exactRegularFile(option(args, '--anchor'), 'anchor')
    const anchor = JSON.parse(await readFile(anchorPath, 'utf8'))
    const result = await verifyPublicFreezeAnchor(anchor)
    process.stdout.write(canonicalJson({ ...result, anchorSha256: sha256(await readFile(anchorPath)), paidModelInvocations: 0 }))
  } else {
    throw new Error('usage: attestation.mjs create|verify|verify-local ...')
  }
}
